### ISSUE TITLE
Can't upload 7.7.10 .gwbk

### ISSUE THREAD

**Issue by olesbober** [paul-griffith/kindling#35]
Tried uploading a 7.7.10 .gwbk and it failed with error:

Cannot invoke "org.w3c.dom.Node.getTextContext()" because the return value of "org.w3c.dom.NodeList.item(int)" is null

Gateway backup loads perfectly fine onto a fresh 7.7.10 install.

Below is a screenshot of the root directory of the .gwbk in question.
![image](https://user-images.githubusercontent.com/28419536/154741266-096d5ea6-fde4-44be-9f40-63b9e25d96a6.png)

**Comment by paul-griffith** [comment]
```stacktrace
java.lang.NullPointerException: Cannot invoke "org.w3c.dom.Node.getTextContent()" because the return value of "org.w3c.dom.NodeList.item(int)" is null
	at io.github.paulgriffith.backup.BackupView.<init>(BackupView.kt:39)
	at io.github.paulgriffith.utils.Tool$BackupViewer.open(Tool.kt:86)
	at io.github.paulgriffith.MainPanel.safeOpen(MainPanel.kt:91)
	at io.github.paulgriffith.MainPanel.openFiles(MainPanel.kt:127)
	at io.github.paulgriffith.MainPanel$openAction$1.invoke(MainPanel.kt:57)
	at io.github.paulgriffith.MainPanel$openAction$1.invoke(MainPanel.kt:54)
	at io.github.paulgriffith.utils.Action.actionPerformed(Action.kt:31)
	at io.github.paulgriffith.MainPanel$Companion.main$lambda-2(MainPanel.kt:178)
	at java.desktop/java.awt.event.InvocationEvent.dispatch$$$capture(InvocationEvent.java:318)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:771)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
```
Makes sense - `edition` is missing, because this .gwbk far predates Edge, let alone Maker. Should be an easy fix.
